### PR TITLE
[2.x] Flush Vite per-request state

### LINKED ISSUE #992: Memory leak in Illuminate/Foundation/Vite ()
### Octane Version

2.6.1

### Laravel Version

11.41.3

### PHP Version

8.3

### What server type are you using?

Roadrunner

### Server Version

any

### Database Driver & Version

_No response_

### Description

`protected $preloadedAssets = [];` in `src/Illuminate/Foundation/Vite.php`
is not flushed  at every request

this cause a problem in `Illuminate\Http\Middleware\AddLinkHeadersForPreloadedAssets`
when a Laravel app is serving several domains. (e.g.  a CMS SaaS with each customer using its own domain).

### Steps To Reproduce

Create laravel app serving more than one domain and see how , Vite::preloadedAssets() will start to be filled with assets of each domain, when it should have assets for the current domain

### PR DESCRIPTION
**Pull request by timacdonald**
Depends on: https://github.com/laravel/framework/pull/55228

Fixes https://github.com/laravel/octane/issues/992

### CODE REVIEW

File: src/Concerns/ProvidesDefaultConfigurationOptions.php [hunk 1]
```diff
@@ -48,11 +48,12 @@ public static function prepareApplicationForNextOperation(): array
             \Laravel\Octane\Listeners\FlushDatabaseRecordModificationState::class,
             \Laravel\Octane\Listeners\FlushDatabaseQueryLog::class,
             \Laravel\Octane\Listeners\RefreshQueryDurationHandling::class,
-            \Laravel\Octane\Listeners\FlushLogContext::class,
             \Laravel\Octane\Listeners\FlushArrayCache::class,
+            \Laravel\Octane\Listeners\FlushLogContext::class,
```
Comment (timacdonald) [inline src/Concerns/ProvidesDefaultConfigurationOptions.php:52]: Sorted the `Flush...` classes.
