### PR TITLE
Fix undefined array key "assets"

### LINKED ISSUE #863: Undefined array key "assets"
### Octane Version

latest

### Laravel Version

11

### PHP Version

8.3

### What server type are you using?

FrankenPHP

### Server Version

latest

### Database Driver & Version

_No response_

### Description

```
php artisan octane:install --server=frankenphp -vvv


 FrankenPHP's Octane integration is in beta and should be used with caution in production. Do you wish to continue? (yes/no) [yes]:
 > 

 Unable to locate FrankenPHP binary. Should Octane download the binary for your operating system? (yes/no) [yes]:
 > 



   ERROR  Undefined array key "assets"
```

### Steps To Reproduce

When I quickly confirm everything and cancel, and then run again it always prompts these

### PR DESCRIPTION
**Pull request by sy-records**
Failure to fetch assets due to API rate limit exceeded, The `RequestException` will now be thrown.

image

close #863

### CODE REVIEW

**Comment by smortexa** [comment]
IMO, it should throw HTTP request exception here.

File: src/Commands/Concerns/InstallsFrankenPhpDependencies.php [hunk 1]
```diff
@@ -71,9 +72,15 @@ protected function downloadFrankenPhpBinary()
...
+        $response = Http::accept('application/vnd.github+json')
             ->withHeaders(['X-GitHub-Api-Version' => '2022-11-28'])
-            ->get('https://api.github.com/repos/dunglas/frankenphp/releases/latest')['assets'];
+            ->get('https://api.github.com/repos/dunglas/frankenphp/releases/latest');
+
+        $assets = $response['assets'] ?? [];
+        if (empty($assets)) {
+            $this->error("Get FrankenPHP's latest release failed, see the response below:");
+            throw new RequestException($response);
+        }
```
Comment (smortexa) [inline src/Commands/Concerns/InstallsFrankenPhpDependencies.php]: @sy-records What about just chaining `->throw()` method on HTTP facade?
