### PR TITLE
Fixes global environment variables not being taken in by workers

### LINKED ISSUE #244: The system environment variables got overrided by the .env
- Octane Version: v0.4.2
- Laravel Version: v8.38.0
- PHP Version: 8.0.3
- Server: Swoole / RoadRunner (Same issue with both runtime)
- Database Driver & Version: Mysql 8.0

### Description:
The system environment variables got override by the .env in Octane but not php-fpm or php-cli.
**The system environment variables shouldn't be override by the .env in Octane.**

### Steps To Reproduce: (max and linux)

1. Test the laravel/octane in composer.json to v0.2.0

```
"laravel/octane": "~0.2.0",
```

2. Add a test route to web.php

```php
Route::get('test-sys-vars', function() {
    var_dump($_ENV['DB_USERNAME']);
    var_dump(config('database.connections.mysql.username'));
    var_dump(getenv('DB_USERNAME'));
    var_dump(getenv('DB_USERNAME', true));
    dd(env('DB_USERNAME'));
});
```

3. Run command in the current Laravel project directory.
```bash
export DB_USERNAME=example-app && php -dvariables_order=EGPCS artisan octane:start --server=roadrunner --host=0.0.0.0 --port=8000
```

4. Make sure DB_USERNAME exists in the .env
```
DB_USERNAME=homestead
```

5. Browse http://localhost:8000/test-sys-vars and see result

Then repeat 1 - 5 again with another version
```
"laravel/octane": "^0.4.0",
```

image

### PR DESCRIPTION
**Pull request by nunomaduro**
This pull request fixes global environment variables not being taken in by workers. In addition, it fixes the fact that the `environment` value was not being taken by workers too.

Fixes #244.

### CODE REVIEW

File: src/Commands/StartRoadRunnerCommand.php [hunk 1]
```diff
@@ -85,13 +89,11 @@ public function handle(ServerProcessInspector $inspector, ServerStateFile $serve
             '-o', 'logs.output=stdout',
             '-o', 'logs.encoding=json',
             '--dotenv=""', 'serve',
```
Comment (48d90782) [inline src/Commands/StartRoadRunnerCommand.php:91]: You can safely delete this CLI arg, by default RR doesn't use dotenv anymore in the latest version.
